### Health Check
GET http://localhost:8000/health

### Create Order
POST http://localhost:8000/api/order
Content-Type: application/json

{
    "customer": {
        "firstName": "Hemanth",
        "lastName": "R",
        "email": "hemanth@example.com",
        "phone": "1234567890"
    },
    "items": [
        {
            "productId": 1,
            "quantity": 2
        },
        {
            "productId": 2,
            "quantity": 1
        }
    ],
    "shippingAmount": 10.00,
    "taxAmount": 5.50
}


### Get Customers
GET http://localhost:8000/api/customer

### Get Products
GET http://localhost:8000/api/product

### Upload Profile Photo
POST http://localhost:8000/api/customer/profile-upload/1
Content-Type: multipart/form-data; boundary=----FormBoundary

------FormBoundary
Content-Disposition: form-data; name="uploaded_file"; filename="photo.png"
Content-Type: image/png

< /Users/hemanthr/Desktop/Screenshot 2026-06-01 at 11.59.52 PM.png
------FormBoundary--
