FROM oven/bun:1 AS deps
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

FROM oven/bun:1 AS release
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY src ./src
COPY logger.ts ./

ENV NODE_ENV=production

USER bun

CMD ["bun", "src/lib/worker.ts"]
